import Head from 'next/head'
import TopCards from '@/components/TopCards'
import CustomerTableOverview from '@/components/CustomerTableOverview'

export default function Home() {
  return (
    <>
    <Head>
      <title>ASA PH</title>
      <meta name='description' content='Generated by create next app'/>
      <meta name='viewport' content='width=device-width, initial-scale=1'/>
      <link rel='icon' href='/assets/ASA-Custom.svg'/>
    </Head>
      <div className='px-5 pt-4 font-bold text-xl'>
        Dashboard
      </div>
      <TopCards/>
      <CustomerTableOverview/>
    </>
  )
}
